[package]
name = "rerast"
version = "0.1.5"
license = "Apache-2.0"
description = "An AST (abstract syntax tree) based search replace tool for code written in Rust"
repository = "https://github.com/google/rerast"
readme = "README.md"
categories = ["development-tools", "development-tools::cargo-plugins"]
authors = [
    "David Lattimore <dvdlttmr@gmail.com>",
]

[dependencies]
rerast_macros = { version = "0.1.0", path = "rerast_macros" }
itertools = "0.5.*"
clap = "2.*"
json = "0.11.10"
diff = "0.1.10"
colored = "1.6.0"
clippy = {version = "0.*", optional = true}
failure = "0.1.1"

[dev-dependencies]
assert_cli = "0.5"

[features]
#default = ["clippy"]
