[package]
name = "rerast"
version = "0.1.80"
license = "Apache-2.0"
description = "An AST (abstract syntax tree) based search replace tool for code written in Rust"
repository = "https://github.com/google/rerast"
readme = "README.md"
categories = ["development-tools", "development-tools::cargo-plugins"]
edition = "2018"
authors = [
    "David Lattimore <dvdlttmr@gmail.com>",
    "Dale Wijnand",
    "Kornel",
]

[dependencies]
rerast_macros = { version = "0.1.12", path = "rerast_macros" }
itertools = "0.8.0"
clap = "2.33.0"
json = "0.11.15"
diff = "0.1.11"
colored = "1.8.0"
failure = "0.1.5"

[dev-dependencies]
predicates = "1.0.1"
assert_cmd = "0.11.1"
